# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFormLayout, QFrame, QGridLayout,
    QHBoxLayout, QLabel, QPushButton, QSizePolicy,
    QSpacerItem, QVBoxLayout, QWidget)

class Ui_commentsWindow(object):
    def setupUi(self, commentsWindow):
        if not commentsWindow.objectName():
            commentsWindow.setObjectName(u"commentsWindow")
        commentsWindow.setWindowModality(Qt.ApplicationModal)
        commentsWindow.resize(953, 771)
        commentsWindow.setMinimumSize(QSize(953, 771))
        commentsWindow.setMaximumSize(QSize(953, 771))
        commentsWindow.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 219, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.formLayout = QFormLayout(commentsWindow)
        self.formLayout.setObjectName(u"formLayout")
        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.line_4 = QFrame(commentsWindow)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)

        self.gridLayout_4.addWidget(self.line_4, 0, 0, 1, 1)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalSpacer = QSpacerItem(18, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.header_label = QLabel(commentsWindow)
        self.header_label.setObjectName(u"header_label")

        self.horizontalLayout.addWidget(self.header_label)

        self.horizontalSpacer_2 = QSpacerItem(18, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)


        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.verticalSpacer_5 = QSpacerItem(20, 18, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_4.addItem(self.verticalSpacer_5, 2, 0, 1, 1)

        self.line = QFrame(commentsWindow)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.gridLayout_4.addWidget(self.line, 3, 0, 1, 1)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalSpacer_9 = QSpacerItem(28, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_9)

        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalSpacer_6 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer_6)

        self.newcommit_button = QPushButton(commentsWindow)
        self.newcommit_button.setObjectName(u"newcommit_button")
        self.newcommit_button.setMinimumSize(QSize(220, 60))
        self.newcommit_button.setMaximumSize(QSize(220, 60))
        self.newcommit_button.setStyleSheet(u"background-color: rgb(85, 255, 255);")

        self.verticalLayout.addWidget(self.newcommit_button)

        self.verticalSpacer = QSpacerItem(20, 30, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.viewcommit_button = QPushButton(commentsWindow)
        self.viewcommit_button.setObjectName(u"viewcommit_button")
        self.viewcommit_button.setMinimumSize(QSize(220, 60))
        self.viewcommit_button.setMaximumSize(QSize(220, 60))
        self.viewcommit_button.setStyleSheet(u"background-color: rgb(0, 255, 255);")

        self.verticalLayout.addWidget(self.viewcommit_button)


        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.verticalSpacer_3 = QSpacerItem(40, 50, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_3.addItem(self.verticalSpacer_3, 1, 0, 1, 1)

        self.horizontalSpacer_7 = QSpacerItem(68, 20, QSizePolicy.Maximum, QSizePolicy.Minimum)

        self.gridLayout_3.addItem(self.horizontalSpacer_7, 0, 1, 1, 1)


        self.horizontalLayout_3.addLayout(self.gridLayout_3)

        self.horizontalSpacer_8 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_8)

        self.line_2 = QFrame(commentsWindow)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)

        self.horizontalLayout_3.addWidget(self.line_2)

        self.horizontalSpacer_11 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_11)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.statistic_label = QLabel(commentsWindow)
        self.statistic_label.setObjectName(u"statistic_label")
        self.statistic_label.setMinimumSize(QSize(320, 80))
        self.statistic_label.setMaximumSize(QSize(320, 80))

        self.gridLayout_2.addWidget(self.statistic_label, 1, 1, 1, 1)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Maximum, QSizePolicy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer_4, 1, 2, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 15, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout_2.addItem(self.verticalSpacer_2, 2, 1, 1, 1)

        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.auditor = QLabel(commentsWindow)
        self.auditor.setObjectName(u"auditor")
        self.auditor.setMinimumSize(QSize(200, 30))
        self.auditor.setMaximumSize(QSize(200, 30))

        self.gridLayout.addWidget(self.auditor, 2, 0, 1, 1)

        self.auditor_label = QLabel(commentsWindow)
        self.auditor_label.setObjectName(u"auditor_label")
        self.auditor_label.setMinimumSize(QSize(80, 30))
        self.auditor_label.setMaximumSize(QSize(80, 30))
        palette = QPalette()
        brush = QBrush(QColor(255, 0, 40, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        gradient = QLinearGradient(0, 0, 1, 1)
        gradient.setSpread(QGradient.PadSpread)
        gradient.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient.setColorAt(0, QColor(0, 219, 255, 255))
        gradient.setColorAt(1, QColor(255, 255, 255, 255))
        brush1 = QBrush(gradient)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        gradient1 = QLinearGradient(0, 0, 1, 1)
        gradient1.setSpread(QGradient.PadSpread)
        gradient1.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient1.setColorAt(0, QColor(0, 219, 255, 255))
        gradient1.setColorAt(1, QColor(255, 255, 255, 255))
        brush2 = QBrush(gradient1)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        gradient2 = QLinearGradient(0, 0, 1, 1)
        gradient2.setSpread(QGradient.PadSpread)
        gradient2.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient2.setColorAt(0, QColor(0, 219, 255, 255))
        gradient2.setColorAt(1, QColor(255, 255, 255, 255))
        brush3 = QBrush(gradient2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        gradient3 = QLinearGradient(0, 0, 1, 1)
        gradient3.setSpread(QGradient.PadSpread)
        gradient3.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient3.setColorAt(0, QColor(0, 219, 255, 255))
        gradient3.setColorAt(1, QColor(255, 255, 255, 255))
        brush4 = QBrush(gradient3)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        gradient4 = QLinearGradient(0, 0, 1, 1)
        gradient4.setSpread(QGradient.PadSpread)
        gradient4.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient4.setColorAt(0, QColor(0, 219, 255, 255))
        gradient4.setColorAt(1, QColor(255, 255, 255, 255))
        brush5 = QBrush(gradient4)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush5)
        gradient5 = QLinearGradient(0, 0, 1, 1)
        gradient5.setSpread(QGradient.PadSpread)
        gradient5.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient5.setColorAt(0, QColor(0, 219, 255, 255))
        gradient5.setColorAt(1, QColor(255, 255, 255, 255))
        brush6 = QBrush(gradient5)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush6)
        brush7 = QBrush(QColor(127, 127, 127, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        gradient6 = QLinearGradient(0, 0, 1, 1)
        gradient6.setSpread(QGradient.PadSpread)
        gradient6.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient6.setColorAt(0, QColor(0, 219, 255, 255))
        gradient6.setColorAt(1, QColor(255, 255, 255, 255))
        brush8 = QBrush(gradient6)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        gradient7 = QLinearGradient(0, 0, 1, 1)
        gradient7.setSpread(QGradient.PadSpread)
        gradient7.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient7.setColorAt(0, QColor(0, 219, 255, 255))
        gradient7.setColorAt(1, QColor(255, 255, 255, 255))
        brush9 = QBrush(gradient7)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush9)
        gradient8 = QLinearGradient(0, 0, 1, 1)
        gradient8.setSpread(QGradient.PadSpread)
        gradient8.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient8.setColorAt(0, QColor(0, 219, 255, 255))
        gradient8.setColorAt(1, QColor(255, 255, 255, 255))
        brush10 = QBrush(gradient8)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        self.auditor_label.setPalette(palette)
        font = QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        self.auditor_label.setFont(font)
        self.auditor_label.setFrameShape(QFrame.WinPanel)

        self.gridLayout.addWidget(self.auditor_label, 2, 1, 1, 1)

        self.ksot = QLabel(commentsWindow)
        self.ksot.setObjectName(u"ksot")
        self.ksot.setMinimumSize(QSize(200, 30))
        self.ksot.setMaximumSize(QSize(200, 30))

        self.gridLayout.addWidget(self.ksot, 4, 0, 1, 1)

        self.ksot_label = QLabel(commentsWindow)
        self.ksot_label.setObjectName(u"ksot_label")
        self.ksot_label.setMinimumSize(QSize(80, 30))
        self.ksot_label.setMaximumSize(QSize(80, 30))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        gradient9 = QLinearGradient(0, 0, 1, 1)
        gradient9.setSpread(QGradient.PadSpread)
        gradient9.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient9.setColorAt(0, QColor(0, 219, 255, 255))
        gradient9.setColorAt(1, QColor(255, 255, 255, 255))
        brush11 = QBrush(gradient9)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush11)
        gradient10 = QLinearGradient(0, 0, 1, 1)
        gradient10.setSpread(QGradient.PadSpread)
        gradient10.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient10.setColorAt(0, QColor(0, 219, 255, 255))
        gradient10.setColorAt(1, QColor(255, 255, 255, 255))
        brush12 = QBrush(gradient10)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush12)
        gradient11 = QLinearGradient(0, 0, 1, 1)
        gradient11.setSpread(QGradient.PadSpread)
        gradient11.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient11.setColorAt(0, QColor(0, 219, 255, 255))
        gradient11.setColorAt(1, QColor(255, 255, 255, 255))
        brush13 = QBrush(gradient11)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        gradient12 = QLinearGradient(0, 0, 1, 1)
        gradient12.setSpread(QGradient.PadSpread)
        gradient12.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient12.setColorAt(0, QColor(0, 219, 255, 255))
        gradient12.setColorAt(1, QColor(255, 255, 255, 255))
        brush14 = QBrush(gradient12)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        gradient13 = QLinearGradient(0, 0, 1, 1)
        gradient13.setSpread(QGradient.PadSpread)
        gradient13.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient13.setColorAt(0, QColor(0, 219, 255, 255))
        gradient13.setColorAt(1, QColor(255, 255, 255, 255))
        brush15 = QBrush(gradient13)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush15)
        gradient14 = QLinearGradient(0, 0, 1, 1)
        gradient14.setSpread(QGradient.PadSpread)
        gradient14.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient14.setColorAt(0, QColor(0, 219, 255, 255))
        gradient14.setColorAt(1, QColor(255, 255, 255, 255))
        brush16 = QBrush(gradient14)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush16)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        gradient15 = QLinearGradient(0, 0, 1, 1)
        gradient15.setSpread(QGradient.PadSpread)
        gradient15.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient15.setColorAt(0, QColor(0, 219, 255, 255))
        gradient15.setColorAt(1, QColor(255, 255, 255, 255))
        brush17 = QBrush(gradient15)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush17)
        gradient16 = QLinearGradient(0, 0, 1, 1)
        gradient16.setSpread(QGradient.PadSpread)
        gradient16.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient16.setColorAt(0, QColor(0, 219, 255, 255))
        gradient16.setColorAt(1, QColor(255, 255, 255, 255))
        brush18 = QBrush(gradient16)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush18)
        gradient17 = QLinearGradient(0, 0, 1, 1)
        gradient17.setSpread(QGradient.PadSpread)
        gradient17.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient17.setColorAt(0, QColor(0, 219, 255, 255))
        gradient17.setColorAt(1, QColor(255, 255, 255, 255))
        brush19 = QBrush(gradient17)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush19)
        self.ksot_label.setPalette(palette1)
        self.ksot_label.setFont(font)
        self.ksot_label.setFrameShape(QFrame.WinPanel)

        self.gridLayout.addWidget(self.ksot_label, 4, 1, 1, 1)

        self.foreman = QLabel(commentsWindow)
        self.foreman.setObjectName(u"foreman")
        self.foreman.setMinimumSize(QSize(220, 30))
        self.foreman.setMaximumSize(QSize(220, 30))

        self.gridLayout.addWidget(self.foreman, 5, 0, 1, 1)

        self.foreman_label = QLabel(commentsWindow)
        self.foreman_label.setObjectName(u"foreman_label")
        self.foreman_label.setMinimumSize(QSize(80, 30))
        self.foreman_label.setMaximumSize(QSize(80, 30))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        gradient18 = QLinearGradient(0, 0, 1, 1)
        gradient18.setSpread(QGradient.PadSpread)
        gradient18.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient18.setColorAt(0, QColor(0, 219, 255, 255))
        gradient18.setColorAt(1, QColor(255, 255, 255, 255))
        brush20 = QBrush(gradient18)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush20)
        gradient19 = QLinearGradient(0, 0, 1, 1)
        gradient19.setSpread(QGradient.PadSpread)
        gradient19.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient19.setColorAt(0, QColor(0, 219, 255, 255))
        gradient19.setColorAt(1, QColor(255, 255, 255, 255))
        brush21 = QBrush(gradient19)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush21)
        gradient20 = QLinearGradient(0, 0, 1, 1)
        gradient20.setSpread(QGradient.PadSpread)
        gradient20.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient20.setColorAt(0, QColor(0, 219, 255, 255))
        gradient20.setColorAt(1, QColor(255, 255, 255, 255))
        brush22 = QBrush(gradient20)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush22)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        gradient21 = QLinearGradient(0, 0, 1, 1)
        gradient21.setSpread(QGradient.PadSpread)
        gradient21.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient21.setColorAt(0, QColor(0, 219, 255, 255))
        gradient21.setColorAt(1, QColor(255, 255, 255, 255))
        brush23 = QBrush(gradient21)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush23)
        gradient22 = QLinearGradient(0, 0, 1, 1)
        gradient22.setSpread(QGradient.PadSpread)
        gradient22.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient22.setColorAt(0, QColor(0, 219, 255, 255))
        gradient22.setColorAt(1, QColor(255, 255, 255, 255))
        brush24 = QBrush(gradient22)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush24)
        gradient23 = QLinearGradient(0, 0, 1, 1)
        gradient23.setSpread(QGradient.PadSpread)
        gradient23.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient23.setColorAt(0, QColor(0, 219, 255, 255))
        gradient23.setColorAt(1, QColor(255, 255, 255, 255))
        brush25 = QBrush(gradient23)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush25)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        gradient24 = QLinearGradient(0, 0, 1, 1)
        gradient24.setSpread(QGradient.PadSpread)
        gradient24.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient24.setColorAt(0, QColor(0, 219, 255, 255))
        gradient24.setColorAt(1, QColor(255, 255, 255, 255))
        brush26 = QBrush(gradient24)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush26)
        gradient25 = QLinearGradient(0, 0, 1, 1)
        gradient25.setSpread(QGradient.PadSpread)
        gradient25.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient25.setColorAt(0, QColor(0, 219, 255, 255))
        gradient25.setColorAt(1, QColor(255, 255, 255, 255))
        brush27 = QBrush(gradient25)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush27)
        gradient26 = QLinearGradient(0, 0, 1, 1)
        gradient26.setSpread(QGradient.PadSpread)
        gradient26.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient26.setColorAt(0, QColor(0, 219, 255, 255))
        gradient26.setColorAt(1, QColor(255, 255, 255, 255))
        brush28 = QBrush(gradient26)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush28)
        self.foreman_label.setPalette(palette2)
        self.foreman_label.setFont(font)
        self.foreman_label.setFrameShape(QFrame.WinPanel)

        self.gridLayout.addWidget(self.foreman_label, 5, 1, 1, 1)

        self.total = QLabel(commentsWindow)
        self.total.setObjectName(u"total")
        self.total.setMinimumSize(QSize(220, 30))
        self.total.setMaximumSize(QSize(220, 30))

        self.gridLayout.addWidget(self.total, 6, 0, 1, 1)

        self.total_label = QLabel(commentsWindow)
        self.total_label.setObjectName(u"total_label")
        self.total_label.setMinimumSize(QSize(80, 30))
        self.total_label.setMaximumSize(QSize(80, 30))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        gradient27 = QLinearGradient(0, 0, 1, 1)
        gradient27.setSpread(QGradient.PadSpread)
        gradient27.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient27.setColorAt(0, QColor(0, 219, 255, 255))
        gradient27.setColorAt(1, QColor(255, 255, 255, 255))
        brush29 = QBrush(gradient27)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush29)
        gradient28 = QLinearGradient(0, 0, 1, 1)
        gradient28.setSpread(QGradient.PadSpread)
        gradient28.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient28.setColorAt(0, QColor(0, 219, 255, 255))
        gradient28.setColorAt(1, QColor(255, 255, 255, 255))
        brush30 = QBrush(gradient28)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush30)
        gradient29 = QLinearGradient(0, 0, 1, 1)
        gradient29.setSpread(QGradient.PadSpread)
        gradient29.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient29.setColorAt(0, QColor(0, 219, 255, 255))
        gradient29.setColorAt(1, QColor(255, 255, 255, 255))
        brush31 = QBrush(gradient29)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush31)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        gradient30 = QLinearGradient(0, 0, 1, 1)
        gradient30.setSpread(QGradient.PadSpread)
        gradient30.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient30.setColorAt(0, QColor(0, 219, 255, 255))
        gradient30.setColorAt(1, QColor(255, 255, 255, 255))
        brush32 = QBrush(gradient30)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush32)
        gradient31 = QLinearGradient(0, 0, 1, 1)
        gradient31.setSpread(QGradient.PadSpread)
        gradient31.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient31.setColorAt(0, QColor(0, 219, 255, 255))
        gradient31.setColorAt(1, QColor(255, 255, 255, 255))
        brush33 = QBrush(gradient31)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush33)
        gradient32 = QLinearGradient(0, 0, 1, 1)
        gradient32.setSpread(QGradient.PadSpread)
        gradient32.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient32.setColorAt(0, QColor(0, 219, 255, 255))
        gradient32.setColorAt(1, QColor(255, 255, 255, 255))
        brush34 = QBrush(gradient32)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush34)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        gradient33 = QLinearGradient(0, 0, 1, 1)
        gradient33.setSpread(QGradient.PadSpread)
        gradient33.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient33.setColorAt(0, QColor(0, 219, 255, 255))
        gradient33.setColorAt(1, QColor(255, 255, 255, 255))
        brush35 = QBrush(gradient33)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush35)
        gradient34 = QLinearGradient(0, 0, 1, 1)
        gradient34.setSpread(QGradient.PadSpread)
        gradient34.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient34.setColorAt(0, QColor(0, 219, 255, 255))
        gradient34.setColorAt(1, QColor(255, 255, 255, 255))
        brush36 = QBrush(gradient34)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush36)
        gradient35 = QLinearGradient(0, 0, 1, 1)
        gradient35.setSpread(QGradient.PadSpread)
        gradient35.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient35.setColorAt(0, QColor(0, 219, 255, 255))
        gradient35.setColorAt(1, QColor(255, 255, 255, 255))
        brush37 = QBrush(gradient35)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush37)
        self.total_label.setPalette(palette3)
        self.total_label.setFont(font)
        self.total_label.setFrameShape(QFrame.WinPanel)

        self.gridLayout.addWidget(self.total_label, 6, 1, 1, 1)

        self.safetyday = QLabel(commentsWindow)
        self.safetyday.setObjectName(u"safetyday")
        self.safetyday.setMinimumSize(QSize(200, 30))
        self.safetyday.setMaximumSize(QSize(200, 30))

        self.gridLayout.addWidget(self.safetyday, 3, 0, 1, 1)

        self.safetyday_label = QLabel(commentsWindow)
        self.safetyday_label.setObjectName(u"safetyday_label")
        self.safetyday_label.setMinimumSize(QSize(80, 30))
        self.safetyday_label.setMaximumSize(QSize(80, 30))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        gradient36 = QLinearGradient(0, 0, 1, 1)
        gradient36.setSpread(QGradient.PadSpread)
        gradient36.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient36.setColorAt(0, QColor(0, 219, 255, 255))
        gradient36.setColorAt(1, QColor(255, 255, 255, 255))
        brush38 = QBrush(gradient36)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush38)
        gradient37 = QLinearGradient(0, 0, 1, 1)
        gradient37.setSpread(QGradient.PadSpread)
        gradient37.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient37.setColorAt(0, QColor(0, 219, 255, 255))
        gradient37.setColorAt(1, QColor(255, 255, 255, 255))
        brush39 = QBrush(gradient37)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush39)
        gradient38 = QLinearGradient(0, 0, 1, 1)
        gradient38.setSpread(QGradient.PadSpread)
        gradient38.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient38.setColorAt(0, QColor(0, 219, 255, 255))
        gradient38.setColorAt(1, QColor(255, 255, 255, 255))
        brush40 = QBrush(gradient38)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush40)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        gradient39 = QLinearGradient(0, 0, 1, 1)
        gradient39.setSpread(QGradient.PadSpread)
        gradient39.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient39.setColorAt(0, QColor(0, 219, 255, 255))
        gradient39.setColorAt(1, QColor(255, 255, 255, 255))
        brush41 = QBrush(gradient39)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush41)
        gradient40 = QLinearGradient(0, 0, 1, 1)
        gradient40.setSpread(QGradient.PadSpread)
        gradient40.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient40.setColorAt(0, QColor(0, 219, 255, 255))
        gradient40.setColorAt(1, QColor(255, 255, 255, 255))
        brush42 = QBrush(gradient40)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush42)
        gradient41 = QLinearGradient(0, 0, 1, 1)
        gradient41.setSpread(QGradient.PadSpread)
        gradient41.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient41.setColorAt(0, QColor(0, 219, 255, 255))
        gradient41.setColorAt(1, QColor(255, 255, 255, 255))
        brush43 = QBrush(gradient41)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush43)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        gradient42 = QLinearGradient(0, 0, 1, 1)
        gradient42.setSpread(QGradient.PadSpread)
        gradient42.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient42.setColorAt(0, QColor(0, 219, 255, 255))
        gradient42.setColorAt(1, QColor(255, 255, 255, 255))
        brush44 = QBrush(gradient42)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush44)
        gradient43 = QLinearGradient(0, 0, 1, 1)
        gradient43.setSpread(QGradient.PadSpread)
        gradient43.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient43.setColorAt(0, QColor(0, 219, 255, 255))
        gradient43.setColorAt(1, QColor(255, 255, 255, 255))
        brush45 = QBrush(gradient43)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush45)
        gradient44 = QLinearGradient(0, 0, 1, 1)
        gradient44.setSpread(QGradient.PadSpread)
        gradient44.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient44.setColorAt(0, QColor(0, 219, 255, 255))
        gradient44.setColorAt(1, QColor(255, 255, 255, 255))
        brush46 = QBrush(gradient44)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush46)
        self.safetyday_label.setPalette(palette4)
        self.safetyday_label.setFont(font)
        self.safetyday_label.setFrameShape(QFrame.WinPanel)

        self.gridLayout.addWidget(self.safetyday_label, 3, 1, 1, 1)

        self.deputy = QLabel(commentsWindow)
        self.deputy.setObjectName(u"deputy")
        self.deputy.setMinimumSize(QSize(200, 30))
        self.deputy.setMaximumSize(QSize(200, 30))

        self.gridLayout.addWidget(self.deputy, 1, 0, 1, 1)

        self.deputy_label = QLabel(commentsWindow)
        self.deputy_label.setObjectName(u"deputy_label")
        self.deputy_label.setMinimumSize(QSize(80, 30))
        self.deputy_label.setMaximumSize(QSize(80, 30))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        gradient45 = QLinearGradient(0, 0, 1, 1)
        gradient45.setSpread(QGradient.PadSpread)
        gradient45.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient45.setColorAt(0, QColor(0, 219, 255, 255))
        gradient45.setColorAt(1, QColor(255, 255, 255, 255))
        brush47 = QBrush(gradient45)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush47)
        gradient46 = QLinearGradient(0, 0, 1, 1)
        gradient46.setSpread(QGradient.PadSpread)
        gradient46.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient46.setColorAt(0, QColor(0, 219, 255, 255))
        gradient46.setColorAt(1, QColor(255, 255, 255, 255))
        brush48 = QBrush(gradient46)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush48)
        gradient47 = QLinearGradient(0, 0, 1, 1)
        gradient47.setSpread(QGradient.PadSpread)
        gradient47.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient47.setColorAt(0, QColor(0, 219, 255, 255))
        gradient47.setColorAt(1, QColor(255, 255, 255, 255))
        brush49 = QBrush(gradient47)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush49)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        gradient48 = QLinearGradient(0, 0, 1, 1)
        gradient48.setSpread(QGradient.PadSpread)
        gradient48.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient48.setColorAt(0, QColor(0, 219, 255, 255))
        gradient48.setColorAt(1, QColor(255, 255, 255, 255))
        brush50 = QBrush(gradient48)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush50)
        gradient49 = QLinearGradient(0, 0, 1, 1)
        gradient49.setSpread(QGradient.PadSpread)
        gradient49.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient49.setColorAt(0, QColor(0, 219, 255, 255))
        gradient49.setColorAt(1, QColor(255, 255, 255, 255))
        brush51 = QBrush(gradient49)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush51)
        gradient50 = QLinearGradient(0, 0, 1, 1)
        gradient50.setSpread(QGradient.PadSpread)
        gradient50.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient50.setColorAt(0, QColor(0, 219, 255, 255))
        gradient50.setColorAt(1, QColor(255, 255, 255, 255))
        brush52 = QBrush(gradient50)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush52)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        gradient51 = QLinearGradient(0, 0, 1, 1)
        gradient51.setSpread(QGradient.PadSpread)
        gradient51.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient51.setColorAt(0, QColor(0, 219, 255, 255))
        gradient51.setColorAt(1, QColor(255, 255, 255, 255))
        brush53 = QBrush(gradient51)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush53)
        gradient52 = QLinearGradient(0, 0, 1, 1)
        gradient52.setSpread(QGradient.PadSpread)
        gradient52.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient52.setColorAt(0, QColor(0, 219, 255, 255))
        gradient52.setColorAt(1, QColor(255, 255, 255, 255))
        brush54 = QBrush(gradient52)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush54)
        gradient53 = QLinearGradient(0, 0, 1, 1)
        gradient53.setSpread(QGradient.PadSpread)
        gradient53.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient53.setColorAt(0, QColor(0, 219, 255, 255))
        gradient53.setColorAt(1, QColor(255, 255, 255, 255))
        brush55 = QBrush(gradient53)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush55)
        self.deputy_label.setPalette(palette5)
        self.deputy_label.setFont(font)
        self.deputy_label.setFrameShape(QFrame.WinPanel)

        self.gridLayout.addWidget(self.deputy_label, 1, 1, 1, 1)

        self.boss = QLabel(commentsWindow)
        self.boss.setObjectName(u"boss")
        self.boss.setMinimumSize(QSize(200, 30))
        self.boss.setMaximumSize(QSize(200, 30))

        self.gridLayout.addWidget(self.boss, 0, 0, 1, 1)

        self.boss_label = QLabel(commentsWindow)
        self.boss_label.setObjectName(u"boss_label")
        self.boss_label.setMinimumSize(QSize(80, 30))
        self.boss_label.setMaximumSize(QSize(80, 30))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        gradient54 = QLinearGradient(0, 0, 1, 1)
        gradient54.setSpread(QGradient.PadSpread)
        gradient54.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient54.setColorAt(0, QColor(0, 219, 255, 255))
        gradient54.setColorAt(1, QColor(255, 255, 255, 255))
        brush56 = QBrush(gradient54)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush56)
        gradient55 = QLinearGradient(0, 0, 1, 1)
        gradient55.setSpread(QGradient.PadSpread)
        gradient55.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient55.setColorAt(0, QColor(0, 219, 255, 255))
        gradient55.setColorAt(1, QColor(255, 255, 255, 255))
        brush57 = QBrush(gradient55)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush57)
        gradient56 = QLinearGradient(0, 0, 1, 1)
        gradient56.setSpread(QGradient.PadSpread)
        gradient56.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient56.setColorAt(0, QColor(0, 219, 255, 255))
        gradient56.setColorAt(1, QColor(255, 255, 255, 255))
        brush58 = QBrush(gradient56)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush58)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        gradient57 = QLinearGradient(0, 0, 1, 1)
        gradient57.setSpread(QGradient.PadSpread)
        gradient57.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient57.setColorAt(0, QColor(0, 219, 255, 255))
        gradient57.setColorAt(1, QColor(255, 255, 255, 255))
        brush59 = QBrush(gradient57)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush59)
        gradient58 = QLinearGradient(0, 0, 1, 1)
        gradient58.setSpread(QGradient.PadSpread)
        gradient58.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient58.setColorAt(0, QColor(0, 219, 255, 255))
        gradient58.setColorAt(1, QColor(255, 255, 255, 255))
        brush60 = QBrush(gradient58)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush60)
        gradient59 = QLinearGradient(0, 0, 1, 1)
        gradient59.setSpread(QGradient.PadSpread)
        gradient59.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient59.setColorAt(0, QColor(0, 219, 255, 255))
        gradient59.setColorAt(1, QColor(255, 255, 255, 255))
        brush61 = QBrush(gradient59)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush61)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        gradient60 = QLinearGradient(0, 0, 1, 1)
        gradient60.setSpread(QGradient.PadSpread)
        gradient60.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient60.setColorAt(0, QColor(0, 219, 255, 255))
        gradient60.setColorAt(1, QColor(255, 255, 255, 255))
        brush62 = QBrush(gradient60)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush62)
        gradient61 = QLinearGradient(0, 0, 1, 1)
        gradient61.setSpread(QGradient.PadSpread)
        gradient61.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient61.setColorAt(0, QColor(0, 219, 255, 255))
        gradient61.setColorAt(1, QColor(255, 255, 255, 255))
        brush63 = QBrush(gradient61)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush63)
        gradient62 = QLinearGradient(0, 0, 1, 1)
        gradient62.setSpread(QGradient.PadSpread)
        gradient62.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient62.setColorAt(0, QColor(0, 219, 255, 255))
        gradient62.setColorAt(1, QColor(255, 255, 255, 255))
        brush64 = QBrush(gradient62)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush64)
        self.boss_label.setPalette(palette6)
        self.boss_label.setFont(font)
        self.boss_label.setFrameShape(QFrame.WinPanel)

        self.gridLayout.addWidget(self.boss_label, 0, 1, 1, 1)

        self.verticalSpacer_7 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout.addItem(self.verticalSpacer_7, 7, 0, 1, 1)


        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 3)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Maximum, QSizePolicy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer_3, 1, 0, 1, 1)

        self.verticalSpacer_8 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Preferred)

        self.gridLayout_2.addItem(self.verticalSpacer_8, 0, 1, 1, 1)


        self.horizontalLayout_3.addLayout(self.gridLayout_2)

        self.horizontalSpacer_10 = QSpacerItem(18, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_10)


        self.gridLayout_4.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)

        self.verticalSpacer_4 = QSpacerItem(20, 28, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_4.addItem(self.verticalSpacer_4, 5, 0, 1, 1)

        self.line_3 = QFrame(commentsWindow)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)

        self.gridLayout_4.addWidget(self.line_3, 6, 0, 1, 1)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalSpacer_5 = QSpacerItem(758, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_5)

        self.return_button = QPushButton(commentsWindow)
        self.return_button.setObjectName(u"return_button")
        self.return_button.setMinimumSize(QSize(100, 30))
        self.return_button.setMaximumSize(QSize(100, 30))

        self.horizontalLayout_2.addWidget(self.return_button)

        self.horizontalSpacer_6 = QSpacerItem(28, 20, QSizePolicy.Maximum, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_6)


        self.gridLayout_4.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)


        self.formLayout.setLayout(0, QFormLayout.LabelRole, self.gridLayout_4)


        self.retranslateUi(commentsWindow)

        QMetaObject.connectSlotsByName(commentsWindow)
    # setupUi

    def retranslateUi(self, commentsWindow):
        commentsWindow.setWindowTitle(QCoreApplication.translate("commentsWindow", u"\u0417\u0430\u043c\u0435\u0447\u0430\u043d\u0438\u044f", None))
        self.header_label.setText(QCoreApplication.translate("commentsWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; font-style:italic; color:#f5029b;\">\u041c\u043e\u0434\u0443\u043b\u044c \u0440\u0430\u0431\u043e\u0442\u044b \u0441 \u0437\u0430\u043c\u0435\u0447\u0430\u043d\u0438\u044f\u043c\u0438 </span></p></body></html>", None))
        self.newcommit_button.setText(QCoreApplication.translate("commentsWindow", u"\u0412\u0432\u043e\u0434 \u043d\u043e\u0432\u044b\u0445 \n"
" \u0437\u0430\u043c\u0435\u0447\u0430\u043d\u0438\u0439", None))
        self.viewcommit_button.setText(QCoreApplication.translate("commentsWindow", u"\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u0438 \n"
" \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u0437\u0430\u043c\u0435\u0447\u0430\u043d\u0438\u0439", None))
        self.statistic_label.setText(QCoreApplication.translate("commentsWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; color:#310db5;\">\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u043d\u0435\u0443\u0441\u0442\u0440\u0430\u043d\u0435\u043d\u043d\u044b\u0445</span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; color:#310db5;\">\u0437\u0430\u043c\u0435\u0447\u0430\u043d\u0438\u0439</span></p></body></html>", None))
        self.auditor.setText(QCoreApplication.translate("commentsWindow", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#3fb507;\">\u0420\u0435\u0432\u0438\u0437\u043e\u0440\u0441\u043a\u0438\u0439 \u0430\u043f\u043f\u0430\u0440\u0430\u0442:</span></p></body></html>", None))
        self.auditor_label.setText("")
        self.ksot.setText(QCoreApplication.translate("commentsWindow", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#3fb507;\">\u041e\u0445\u0440\u0430\u043d\u0430 \u0442\u0440\u0443\u0434\u0430:</span></p></body></html>", None))
        self.ksot_label.setText("")
        self.foreman.setText(QCoreApplication.translate("commentsWindow", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#3fb507;\">\u0421\u0442\u0430\u0440\u0448\u0438\u0439 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043c\u0435\u0445\u0430\u043d\u0438\u043a:</span></p></body></html>", None))
        self.foreman_label.setText("")
        self.total.setText(QCoreApplication.translate("commentsWindow", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#f10401;\">\u0418\u0442\u043e\u0433\u043e \u043d\u0435\u0443\u0441\u0442\u0440\u0430\u043d\u0435\u043d\u043d\u044b\u0445:</span></p></body></html>", None))
        self.total_label.setText("")
        self.safetyday.setText(QCoreApplication.translate("commentsWindow", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#3fb507;\">\u0414\u043d\u0438 \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u0438:</span></p></body></html>", None))
        self.safetyday_label.setText("")
        self.deputy.setText(QCoreApplication.translate("commentsWindow", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#3fb507;\">\u0417\u0430\u043c. \u043f\u043e \u0440\u0435\u0433\u0438\u043e\u043d\u0443:</span></p></body></html>", None))
        self.deputy_label.setText("")
        self.boss.setText(QCoreApplication.translate("commentsWindow", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#3fb507;\">\u041d\u0430\u0447\u0430\u043b\u044c\u043d\u0438\u043a \u0434\u043e\u0440\u043e\u0433\u0438:</span></p></body></html>", None))
        self.boss_label.setText("")
        self.return_button.setText(QCoreApplication.translate("commentsWindow", u"\u041d\u0430\u0437\u0430\u0434", None))
    # retranslateUi

